dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.9
branches:
  except:
    - /^v[0-9]/
before_install:
- sudo etc/testing/ci/before_install.sh
before_script:
- sudo touch /etc/resolve.conf
- echo 'pre resolv conf:'
- cat /etc/resolve.conf || true
- sudo echo 'nameserver 8.8.8.8' > /etc/resolv.conf
- echo 'post resolv conf:'
- cat /etc/resolve.conf || true
- sudo systemctl stop systemd-resolved
- sudo systemctl disable systemd-resolved
- make launch-kube
- docker version
# Install any deps used by our "batch test" cron
- etc/testing/ci/travis_install_batch_deps.sh
script:
- make lint vet
- etc/testing/travis.sh
after_failure:
- kubectl version
- kubectl get all
- kubectl describe pod -l app=pachd
notifications:
  slack: pachyderm:qmSCZSX1Q2yWxc6DjNZZFLGd
