apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ppsd
  name: ppsd
spec:
  containers:
  - image: gcr.io/pachyderm-dev-us1/ppsd:1a2bd79
    name: ppsd
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    ports:
    - containerPort: 651
      name: api-port
